spring:
  application:
    name: development-plan
  datasource:
    url: jdbc:postgresql://localhost:5432/deep_dive
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 5000
      max-lifetime: 60000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false

# Optional if using SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
notification:
  service: sms

# resilience4j properties
#resilience4j:
#  retry:
#    instances:
#      orderServiceRetry:
#        max-attempts: 3                  # Total attempts (1 initial call + 2 retries)
#        wait-duration: 2s                # Wait time between attempts
#        enable-exponential-backoff: true # Progressively increase wait time
#        exponential-backoff-multiplier: 2 # wait-duration doubles each retry (2s, 4s...)
#        retry-exceptions:                # Only retry on transient/network errors
#          - java.io.IOException
#          - org.springframework.web.client.HttpServerErrorException
#        ignore-exceptions:               # Fail fast on business errors
#          - java.lang.IllegalArgumentException
